# Copyright 2012 Matt Martz
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

import signal
import sys
import threading
from typing import Annotated, Optional

import typer
from http.client import HTTPSConnection
from rich.table import Table

from speedtest_cli import __version__
from speedtest_cli.compat import HTTP_ERRORS
from speedtest_cli.core import Speedtest
from speedtest_cli.exceptions import (
    ConfigRetrievalError,
    InvalidServerIDType,
    NoMatchedServers,
    ServersRetrievalError,
    SpeedtestCLIError,
    SpeedtestException,
)
from speedtest_cli.results import SpeedtestResults
from speedtest_cli.utils import (
    DEBUG,
    console,
    do_nothing,
    err_console,
    make_rich_callback,
    printer,
)
import speedtest_cli.utils as _utils


def version_callback(value: bool):
    if value:
        print(f"speedtest-cli {__version__}")
        print(f"Python {sys.version.replace(chr(10), '')}")
        raise typer.Exit()


app = typer.Typer(
    help=(
        "Command line interface for testing internet bandwidth using "
        "speedtest.net.\n\n"
        "https://github.com/sivel/speedtest-cli"
    ),
    add_completion=False,
)


@app.command()
def shell(
    no_download: Annotated[bool, typer.Option(
        "--no-download",
        help="Do not perform download test",
    )] = False,
    no_upload: Annotated[bool, typer.Option(
        "--no-upload",
        help="Do not perform upload test",
    )] = False,
    single: Annotated[bool, typer.Option(
        "--single",
        help="Only use a single connection instead of multiple. This simulates a typical file transfer.",
    )] = False,
    bytes_mode: Annotated[bool, typer.Option(
        "--bytes",
        help="Display values in bytes instead of bits. Does not affect the image generated by --share, nor output from --json or --csv",
    )] = False,
    share: Annotated[bool, typer.Option(
        "--share",
        help="Generate and provide a URL to the speedtest.net share results image, not displayed with --csv",
    )] = False,
    simple: Annotated[bool, typer.Option(
        "--simple",
        help="Suppress verbose output, only show basic information",
    )] = False,
    csv: Annotated[bool, typer.Option(
        "--csv",
        help="Suppress verbose output, only show basic information in CSV format. Speeds listed in bit/s and not affected by --bytes",
    )] = False,
    csv_delimiter: Annotated[str, typer.Option(
        "--csv-delimiter",
        help='Single character delimiter to use in CSV output. Default ","',
    )] = ",",
    csv_header: Annotated[bool, typer.Option(
        "--csv-header",
        help="Print CSV headers",
    )] = False,
    json_mode: Annotated[bool, typer.Option(
        "--json",
        help="Suppress verbose output, only show basic information in JSON format. Speeds listed in bit/s and not affected by --bytes",
    )] = False,
    list_servers: Annotated[bool, typer.Option(
        "--list",
        help="Display a list of speedtest.net servers sorted by distance",
    )] = False,
    server: Annotated[Optional[list[int]], typer.Option(
        "--server",
        help="Specify a server ID to test against. Can be supplied multiple times",
    )] = None,
    exclude: Annotated[Optional[list[int]], typer.Option(
        "--exclude",
        help="Exclude a server from selection. Can be supplied multiple times",
    )] = None,
    mini: Annotated[Optional[str], typer.Option(
        "--mini",
        help="URL of the Speedtest Mini server",
    )] = None,
    source: Annotated[Optional[str], typer.Option(
        "--source",
        help="Source IP address to bind to",
    )] = None,
    timeout: Annotated[float, typer.Option(
        "--timeout",
        help="HTTP timeout in seconds. Default 10",
    )] = 10,
    secure: Annotated[bool, typer.Option(
        "--secure",
        help="Use HTTPS instead of HTTP when communicating with speedtest.net operated servers",
    )] = False,
    no_pre_allocate: Annotated[bool, typer.Option(
        "--no-pre-allocate",
        help="Do not pre allocate upload data. Pre allocation is enabled by default to improve upload performance. To support systems with insufficient memory, use this option to avoid a MemoryError",
    )] = False,
    version: Annotated[bool, typer.Option(
        "--version",
        help="Show the version number and exit",
        is_eager=True,
        callback=version_callback,
    )] = False,
    debug: Annotated[bool, typer.Option(
        "--debug",
        hidden=True,
    )] = False,
):
    """Run the full speedtest.net test"""

    shutdown_event = threading.Event()

    signal.signal(signal.SIGINT, ctrl_c(shutdown_event))

    download = not no_download
    upload = not no_upload
    units = ('byte', 8) if bytes_mode else ('bit', 1)
    pre_allocate = not no_pre_allocate

    if not download and not upload:
        raise SpeedtestCLIError('Cannot supply both --no-download and '
                                '--no-upload')

    if len(csv_delimiter) != 1:
        raise SpeedtestCLIError('--csv-delimiter must be a single character')

    if csv_header:
        print(SpeedtestResults.csv_header(delimiter=csv_delimiter))
        raise typer.Exit()

    validate_optional_args(secure)

    if debug:
        _utils.DEBUG = True

    if simple or csv or json_mode:
        quiet = True
    else:
        quiet = False

    if csv or json_mode:
        machine_format = True
    else:
        machine_format = False

    if quiet or debug:
        callback = do_nothing
        use_progress = False
    else:
        use_progress = True
        callback = do_nothing  # will be replaced per-phase

    console.print('Retrieving speedtest.net configuration...') if not quiet else None
    try:
        speedtest = Speedtest(
            source_address=source,
            timeout=timeout,
            secure=secure
        )
    except (ConfigRetrievalError,) + HTTP_ERRORS:
        err_console.print('[bold red]Cannot retrieve speedtest configuration[/bold red]')
        raise SpeedtestCLIError(
            'Cannot retrieve speedtest configuration'
        )

    if list_servers:
        try:
            speedtest.get_servers()
        except (ServersRetrievalError,) + HTTP_ERRORS:
            err_console.print('[bold red]Cannot retrieve speedtest server list[/bold red]')
            raise SpeedtestCLIError(
                'Cannot retrieve speedtest server list'
            )

        table = Table(title="Speedtest.net Servers")
        table.add_column("ID", style="cyan", justify="right")
        table.add_column("Sponsor", style="green")
        table.add_column("Location")
        table.add_column("Distance", justify="right")

        for _, servers_list in sorted(speedtest.servers.items()):
            for s in servers_list:
                table.add_row(
                    str(s['id']),
                    s['sponsor'],
                    f"{s['name']}, {s['country']}",
                    f"{s['d']:0.2f} km",
                )

        console.print(table)
        raise typer.Exit()

    console.print(
        'Testing from %(isp)s (%(ip)s)...' % speedtest.config['client']
    ) if not quiet else None

    if not mini:
        console.print('Retrieving speedtest.net server list...') if not quiet else None
        try:
            speedtest.get_servers(servers=server, exclude=exclude)
        except NoMatchedServers:
            raise SpeedtestCLIError(
                'No matched servers: %s' %
                ', '.join('%s' % s for s in server)
            )
        except (ServersRetrievalError,) + HTTP_ERRORS:
            err_console.print('[bold red]Cannot retrieve speedtest server list[/bold red]')
            raise SpeedtestCLIError(
                'Cannot retrieve speedtest server list'
            )
        except InvalidServerIDType:
            raise SpeedtestCLIError(
                '%s is an invalid server type, must '
                'be an int' % ', '.join('%s' % s for s in server)
            )

        if server and len(server) == 1:
            console.print('Retrieving information for the selected server...') if not quiet else None
        else:
            console.print('Selecting best server based on ping...') if not quiet else None
        speedtest.get_best_server()
    elif mini:
        speedtest.get_best_server(speedtest.set_mini_server(mini))

    results = speedtest.results

    console.print(
        'Hosted by %(sponsor)s (%(name)s) [%(d)0.2f km]: '
        '%(latency)s ms' % results.server
    ) if not quiet else None

    if download:
        if use_progress:
            progress, callback = make_rich_callback(shutdown_event, label="Download")
            with progress:
                speedtest.download(
                    callback=callback,
                    threads=(None, 1)[single]
                )
        else:
            printer('Testing download speed', quiet,
                    end=('', '\n')[bool(debug)])
            speedtest.download(
                callback=callback,
                threads=(None, 1)[single]
            )
        printer('Download: %0.2f M%s/s' %
                ((results.download / 1000.0 / 1000.0) / units[1],
                 units[0]),
                quiet)
    else:
        printer('Skipping download test', quiet)

    if upload:
        if use_progress:
            progress, callback = make_rich_callback(shutdown_event, label="Upload")
            with progress:
                speedtest.upload(
                    callback=callback,
                    pre_allocate=pre_allocate,
                    threads=(None, 1)[single]
                )
        else:
            printer('Testing upload speed', quiet,
                    end=('', '\n')[bool(debug)])
            speedtest.upload(
                callback=callback,
                pre_allocate=pre_allocate,
                threads=(None, 1)[single]
            )
        printer('Upload: %0.2f M%s/s' %
                ((results.upload / 1000.0 / 1000.0) / units[1],
                 units[0]),
                quiet)
    else:
        printer('Skipping upload test', quiet)

    printer('Results:\n%r' % results.dict(), debug=True)

    if not simple and share:
        results.share()

    if simple:
        print('Ping: %s ms\nDownload: %0.2f M%s/s\nUpload: %0.2f M%s/s' %
              (results.ping,
               (results.download / 1000.0 / 1000.0) / units[1],
               units[0],
               (results.upload / 1000.0 / 1000.0) / units[1],
               units[0]))
    elif csv:
        print(results.csv(delimiter=csv_delimiter))
    elif json_mode:
        print(results.json())

    if share and not machine_format:
        printer('Share results: %s' % results.share())


def validate_optional_args(secure):
    """Check if an argument was provided that depends on a module that may
    not be part of the Python standard library.
    """
    optional_args = {
        'secure': ('SSL support', HTTPSConnection),
    }

    if secure and optional_args['secure'][1] is None:
        raise SystemExit('%s is not installed. --secure is '
                         'unavailable' % optional_args['secure'][0])


def ctrl_c(shutdown_event):
    """Catch Ctrl-C key sequence and set a SHUTDOWN_EVENT for our threaded
    operations
    """
    def inner(signum, frame):
        shutdown_event.set()
        err_console.print('\n[bold red]Cancelling...[/bold red]')
        sys.exit(0)
    return inner


def main():
    try:
        app()
    except KeyboardInterrupt:
        err_console.print('\n[bold red]Cancelling...[/bold red]')
    except (SpeedtestException, SystemExit) as e:
        if getattr(e, 'code', 1) not in (0, 2):
            msg = '%s' % e
            if not msg:
                msg = '%r' % e
            err_console.print(f'[bold red]ERROR:[/bold red] {msg}')
            raise SystemExit(1)
